controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

api_login_check:
  path: /api/login
  methods: [POST]

register:
  path: /api/register
  controller: App\Controller\RegisterController::register
  methods: [POST]
